# Generated by Django 2.1.5 on 2020-04-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200403_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='emotion',
        ),
    ]
