# Generated by Django 2.1.5 on 2020-04-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200403_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='emotion',
            new_name='subtitle',
        ),
    ]
